// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The Bank Feeds API is a closed API that is only available to financial institutions that have an established financial services partnership with Xero. If you're an existing financial services partner that wants access, contact your local Partner Manager. If you're a financial institution who wants to provide bank feeds to your business customers, contact us to become a financial services partner.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.xero.com/bankfeeds.xro/1.0") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Searches for feed connections
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of feed connections, with pagination details 
    remote isolated function getFeedConnections(GetFeedConnectionsHeaders headers, *GetFeedConnectionsQueries queries) returns FeedConnections|error {
        string resourcePath = string `/FeedConnections`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates one or more new feed connections
    #
    # + headers - Headers to be sent with the request 
    # + payload - Feed Connection(s) array object in the body 
    # + return - The submitted feed connections, each with its status 
    remote isolated function createFeedConnections(CreateFeedConnectionsHeaders headers, FeedConnections payload) returns FeedConnections|error {
        string resourcePath = string `/FeedConnections`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves a single feed connection by its unique ID
    #
    # + id - Unique identifier for retrieving single object
    # + headers - Headers to be sent with the request 
    # + return - The feed connection matching the given ID 
    remote isolated function getFeedConnection(string id, GetFeedConnectionHeaders headers) returns FeedConnection|error {
        string resourcePath = string `/FeedConnections/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes one or more existing feed connections
    #
    # + headers - Headers to be sent with the request 
    # + payload - Feed Connections array object in the body 
    # + return - The feed connections submitted for deletion, each with its status 
    remote isolated function deleteFeedConnections(DeleteFeedConnectionsHeaders headers, FeedConnections payload) returns FeedConnections|error {
        string resourcePath = string `/FeedConnections/DeleteRequests`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves all statements
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of statements, with pagination details 
    remote isolated function getStatements(GetStatementsHeaders headers, *GetStatementsQueries queries) returns Statements|error {
        string resourcePath = string `/Statements`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates one or more new statements
    #
    # + headers - Headers to be sent with the request 
    # + payload - Statements array of objects in the body 
    # + return - The submitted statements, each with its status 
    remote isolated function createStatements(CreateStatementsHeaders headers, Statements payload) returns Statements|error {
        string resourcePath = string `/Statements`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves a single statement by its unique ID
    #
    # + statementId - statement id for single object
    # + headers - Headers to be sent with the request 
    # + return - The statement matching the given ID 
    remote isolated function getStatement(string statementId, GetStatementHeaders headers) returns Statement|error {
        string resourcePath = string `/Statements/${getEncodedUri(statementId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }
}
