// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Represents the Headers record for the operation: getFeedConnection
public type GetFeedConnectionHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Represents the Queries record for the operation: getStatements
public type GetStatementsQueries record {
    # Page size which specifies how many records per page will be returned (default 10). Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?pageSize=100 to specify page size of 100
    int:Signed32 pageSize?;
    # Page number which specifies the set of records to retrieve. By default the number of the records per set is 10. Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?page=2 to get the second set of the records. When page value is not a number or a negative number, by default, the first set of records is returned
    int:Signed32 page?;
};

# A feed connection that links a financial institution account to a bank account in a Xero organisation
public type FeedConnection record {
    # Xero identifier for a bank account in Xero. Must be included if AccountNumber is not specified
    string accountId?;
    # Country of the bank account, as an ISO-3166 alpha-2 country code
    CountryCode country?;
    # The Account Name will be used for the creation of a new Xero Bank Account if a matching Xero Bank Account is not found
    string accountName?;
    # High level bank account type - BANK CREDITCARD BANK encompasses all bank account types other than credit cards
    "BANK"|"CREDITCARD" accountType?;
    # Currency of the bank account, as an ISO-4217 currency code
    CurrencyCode currency?;
    # GUID used to identify the Account
    string id?;
    # This account identifier is generated by the financial institute (FI). This must be unique for your financial institute
    string accountToken?;
    # String(40) when AccountType is BANK String(4) when AccountType is CREDITCARD The Account Number is used to match the feed to a Xero Bank Account. The API will create a new Xero Bank Account if a match to an existing Xero Bank Account is not found. Only the last 4 digits must be supplied for Credit Card numbers. Must be included if AccountId is not specified
    string accountNumber?;
    # Details of why the feed connection request was rejected
    Error 'error?;
    # the current status of the feed connection
    "PENDING"|"REJECTED" status?;
};

# A bank statement delivered to a feed connection, with its opening and closing balances and statement lines
public type Statement record {
    # Transaction lines of the statement
    StatementLines statementLines?;
    # Closing balance date ISO-8601 YYYY-MM-DD
    string endDate?;
    # Closing balance of the statement
    EndBalance endBalance?;
    # Number of statement lines in the statement
    int statementLineCount?;
    # GUID used to identify the Statement
    string id?;
    # The Xero generated feed connection Id that identifies the Xero Bank Account Container into which the statement should be delivered. This is obtained by calling GET FeedConnections
    string feedConnectionId?;
    # Opening balance date (can be no older than one year from the current date) ISO-8601 YYYY-MM-DD
    string startDate?;
    # Opening balance of the statement
    StartBalance startBalance?;
    # Details of why the statement was rejected
    Error[] errors?;
    # Current status of statements
    "PENDING"|"REJECTED"|"DELIVERED" status?;
};

# Represents the Headers record for the operation: getStatements
public type GetStatementsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # Xero identifier of the application making the request
    @http:Header {name: "Xero-Application-Id"}
    string xeroApplicationId = "00000000-0000-0000-0000-0000000010000";
    # Xero identifier of the user on whose behalf the request is made
    @http:Header {name: "Xero-User-Id"}
    string xeroUserId = "00000000-0000-0000-0000-0000030000000";
};

# The StartBalance plus all the Statement Line Amounts should be equal to the EndBalance Amount
public type EndBalance record {
    # decimal(19,4) unsigned closing balance amount
    decimal amount?;
    # Whether the closing balance is a credit or a debit, from the perspective of the customer
    CreditDebitIndicator creditDebitIndicator?;
};

# On error, the API consumer will receive an HTTP response with a HTTP Status Code of 4xx or 5xx and a Content-Type of application/problem+json
public type Error record {
    # Human readable detailed error description
    string detail?;
    # Human readable high level error description
    string title?;
    # Identifies the type of error
    "invalid-request"|"invalid-application"|"invalid-feed-connection"|"duplicate-statement"|"invalid-end-balance"|"invalid-start-and-end-date"|"invalid-start-date"|"internal-error"|"feed-already-connected-in-current-organisation"|"invalid-end-date"|"statement-not-found"|"feed-connected-in-different-organisation"|"feed-already-connected-in-different-organisation"|"bank-feed-not-found"|"invalid-country-specified"|"invalid-organisation-bank-feeds"|"invalid-organisation-multi-currency"|"invalid-feed-connection-for-organisation"|"invalid-user-role"|"account-not-valid"|"feed-not-found-or-already-deleted" 'type?;
    # The numeric HTTP Status Code, e.g. 404
    int status?;
};

# If the statement balances are credit or debit, the CreditDebitIndicator should be specified from the perspective of the Customer
public type CreditDebitIndicator "CREDIT"|"DEBIT";

# The starting balance of the statement
public type StartBalance record {
    # decimal(19,4) unsigned Opening/closing balance amount
    decimal amount?;
    # Whether the opening balance is a credit or a debit, from the perspective of the customer
    CreditDebitIndicator creditDebitIndicator?;
};

# Represents the Headers record for the operation: getStatement
public type GetStatementHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: createStatements
public type CreateStatementsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# 3 letter alpha code for the ISO-4217 currency code, e.g. USD, AUD
public type CurrencyCode "AED"|"AFN"|"ALL"|"AMD"|"ANG"|"AOA"|"ARS"|"AUD"|"AWG"|"AZN"|"BAM"|"BBD"|"BDT"|"BGN"|"BHD"|"BIF"|"BMD"|"BND"|"BOB"|"BRL"|"BSD"|"BTN"|"BWP"|"BYN"|"BZD"|"CAD"|"CDF"|"CHF"|"CLP"|"CNY"|"COP"|"CRC"|"CUC"|"CUP"|"CVE"|"CZK"|"DJF"|"DKK"|"DOP"|"DZD"|"EGP"|"ERN"|"ETB"|"EUR"|"FJD"|"FKP"|"GBP"|"GEL"|"GGP"|"GHS"|"GIP"|"GMD"|"GNF"|"GTQ"|"GYD"|"HKD"|"HNL"|"HRK"|"HTG"|"HUF"|"IDR"|"ILS"|"IMP"|"INR"|"IQD"|"IRR"|"ISK"|"JEP"|"JMD"|"JOD"|"JPY"|"KES"|"KGS"|"KHR"|"KMF"|"KPW"|"KRW"|"KWD"|"KYD"|"KZT"|"LAK"|"LBP"|"LKR"|"LRD"|"LSL"|"LYD"|"MAD"|"MDL"|"MGA"|"MKD"|"MMK"|"MNT"|"MOP"|"MRU"|"MUR"|"MVR"|"MWK"|"MXN"|"MYR"|"MZN"|"NAD"|"NGN"|"NIO"|"NOK"|"NPR"|"NZD"|"OMR"|"PAB"|"PEN"|"PGK"|"PHP"|"PKR"|"PLN"|"PYG"|"QAR"|"RON"|"RSD"|"RUB"|"RWF"|"SAR"|"SBD"|"SCR"|"SDG"|"SEK"|"SGD"|"SHP"|"SLL"|"SOS"|"SPL"|"SRD"|"STN"|"SVC"|"SYP"|"SZL"|"THB"|"TJS"|"TMT"|"TND"|"TOP"|"TRY"|"TTD"|"TVD"|"TWD"|"TZS"|"UAH"|"UGX"|"USD"|"UYU"|"UZS"|"VEF"|"VND"|"VUV"|"WST"|"XAF"|"XCD"|"XDR"|"XOF"|"XPF"|"YER"|"ZAR"|"ZMW"|"ZMK"|"ZWD";

# Pagination details of the returned page of results
public type Pagination record {
    # Number of pages available
    int pageCount?;
    # Page size which specifies how many records per page will be returned (default 50). Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?pageSize=100 to specify page size of 100
    int pageSize?;
    # Page number which specifies the set of records to retrieve. Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?page=2 to get the second set of the records. When page value is not a number or a negative number, by default, the first set of records is returned
    int page?;
    # Number of items returned
    int itemCount?;
};

# Represents the Headers record for the operation: createFeedConnections
public type CreateFeedConnectionsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Represents the Headers record for the operation: getFeedConnections
public type GetFeedConnectionsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# the lines details for a statement
public type StatementLine record {
    # Optional field to enhance the Description
    string reference?;
    # Descriptive transaction type
    string transactionType?;
    # Typically the merchant or payee name
    string payeeName?;
    # Transaction amount
    decimal amount?;
    # Transaction description
    string description?;
    # The cheque/check number
    string chequeNumber?;
    # Whether the transaction is a credit or a debit, from the perspective of the customer
    CreditDebitIndicator creditDebitIndicator?;
    # Financial institute's internal transaction identifier. If provided this field is factored into duplicate detection
    string transactionId?;
    # The date that the transaction was processed or cleared as seen in internet banking ISO-8601 YYYY-MM-DD
    string postedDate?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://identity.xero.com/connect/token";
|};

# Represents the Headers record for the operation: deleteFeedConnections
public type DeleteFeedConnectionsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# The transaction lines of a statement
public type StatementLines StatementLine[];

# A page of statements, or the statements submitted in a create request
public type Statements record {
    # Pagination details of the returned page of results
    Pagination pagination?;
    # List of statements
    Statement[] items?;
};

# ISO-3166 alpha-2 country code, e.g. US, AU This element is required only when the Application supports multi-region. Talk to your Partner Manager to confirm if this is the case
public type CountryCode "AD"|"AE"|"AF"|"AG"|"AI"|"AL"|"AM"|"AN"|"AO"|"AQ"|"AR"|"AS"|"AT"|"AU"|"AW"|"AZ"|"BA"|"BB"|"BD"|"BE"|"BF"|"BG"|"BH"|"BI"|"BJ"|"BL"|"BM"|"BN"|"BO"|"BR"|"BS"|"BT"|"BW"|"BY"|"BZ"|"CA"|"CC"|"CD"|"CF"|"CG"|"CH"|"CI"|"CK"|"CL"|"CM"|"CN"|"CO"|"CR"|"CU"|"CV"|"CW"|"CX"|"CY"|"CZ"|"DE"|"DJ"|"DK"|"DM"|"DO"|"DZ"|"EC"|"EE"|"EG"|"EH"|"ER"|"ES"|"ET"|"FI"|"FJ"|"FK"|"FM"|"FO"|"FR"|"GA"|"GB"|"GD"|"GE"|"GG"|"GH"|"GI"|"GL"|"GM"|"GN"|"GQ"|"GR"|"GT"|"GU"|"GW"|"GY"|"HK"|"HN"|"HR"|"HT"|"HU"|"ID"|"IE"|"IL"|"IM"|"IN"|"IO"|"IQ"|"IR"|"IS"|"IT"|"JE"|"JM"|"JO"|"JP"|"KE"|"KG"|"KH"|"KI"|"KM"|"KN"|"KP"|"KR"|"KW"|"KY"|"KZ"|"LA"|"LB"|"LC"|"LI"|"LK"|"LR"|"LS"|"LT"|"LU"|"LV"|"LY"|"MA"|"MC"|"MD"|"ME"|"MF"|"MG"|"MH"|"MK"|"ML"|"MM"|"MN"|"MO"|"MP"|"MR"|"MS"|"MT"|"MU"|"MV"|"MW"|"MX"|"MY"|"MZ"|"NA"|"NC"|"NE"|"NG"|"NI"|"NL"|"NO"|"NP"|"NR"|"NU"|"NZ"|"OM"|"PA"|"PE"|"PF"|"PG"|"PH"|"PK"|"PL"|"PM"|"PN"|"PR"|"PS"|"PT"|"PW"|"PY"|"QA"|"RE"|"RO"|"RS"|"RU"|"RW"|"SA"|"SB"|"SC"|"SD"|"SE"|"SG"|"SH"|"SI"|"SJ"|"SK"|"SL"|"SM"|"SN"|"SO"|"SR"|"SS"|"ST"|"SV"|"SX"|"SY"|"SZ"|"TC"|"TD"|"TG"|"TH"|"TJ"|"TK"|"TL"|"TM"|"TN"|"TO"|"TR"|"TT"|"TV"|"TW"|"TZ"|"UA"|"UG"|"US"|"UY"|"UZ"|"VA"|"VC"|"VE"|"VG"|"VI"|"VN"|"VU"|"WF"|"WS"|"XK"|"YE"|"YT"|"ZA"|"ZM"|"ZW";

# A page of feed connections, or the feed connections submitted in a create or delete request
public type FeedConnections record {
    # Pagination details of the returned page of results
    Pagination pagination?;
    # List of feed connections
    FeedConnection[] items?;
};

# Represents the Queries record for the operation: getFeedConnections
public type GetFeedConnectionsQueries record {
    # Page size which specifies how many records per page will be returned (default 10). Example - https://api.xero.com/bankfeeds.xro/1.0/FeedConnections?pageSize=100 to specify page size of 100
    int pageSize?;
    # Page number which specifies the set of records to retrieve. By default the number of the records per set is 10. Example - https://api.xero.com/bankfeeds.xro/1.0/FeedConnections?page=2 to get the second set of the records. When page value is not a number or a negative number, by default, the first set of records is returned
    int page?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
